### ISSUE TITLE
Audio only extraction

### ISSUE THREAD

**Issue by bc** [Kagami/webm.py#11]
I see that it supports Opus, but is there a way to use this tool to turn an audio-only webm (mimetype "audio/webm;codecs=opus") into a wav/mp3, etc? thanks so much

**Comment by Kagami** [comment]
You can use ffmpeg for that:

```
ffmpeg -i in.webm out.wav
ffmpeg -i in.webm -b:a 128k out.mp3
```

**Comment by bc** [comment]
awesome thank you!
